project:
  type: website
  post-render: replace-search-index.ts
  resources:
    - "/assets/germany.geojson"
    - "/assets/locations.json"
    - "/assets/iihrn-social-card.png"

website:
  title: "Is it hot right now?"
  site-url: "https://dynamic-manatee-765ec3.netlify.app"
  favicon: /assets/iihrn-favicon-96p.png
  search:
    type: textbox
  google-analytics: ""
  open-graph:
    description: Is it hot right now, or does it just feel like it?
    image: "/assets/iihrn-social-card.png"
  twitter-card:
    site: "isithotrightnow.com"
    description: Is it hot right now, or does it just feel like it?
    card-style: "summary"
    image: "/assets/iihrn-social-card.png"
  navbar:
    background: "#ffffff"
    collapse: false
  page-footer:
    left: |
        <p style="font-size: 1.5em;">By <a href="https://theurbanist.com.au/about">Mat Lipson</a>, <a href="https://steefancontractor.github.io/my_website/">Steefan Contractor</a> and <a href="https://jamesgoldie.dev">James Goldie</a>.</p>
        <p style="font-size: 1.5em;"><a href="mailto:isithotrightnow@gmail.com">Get in touch!</a></p>
    right: |
        <p>Our data comes from the Bureau of Meteorology's <a href="http://www.bom.gov.au/climate/change/acorn-sat/">ACORN-SAT</a> and latest XML feeds.</p>
        <p>Our graphics are <a href="/licence">free to share for non-commercial purposes</a>.</p>
        <a href="https://creativecommons.org/licenses/by-nc/4.0/"><img src="https://mirrors.creativecommons.org/presskit/buttons/88x31/png/by-nc.png" alt="Creative Commons Attribution Non-Commercial 4.0 badge" style="width:80px"/></a>

format:
  html:
    theme:
      - default
      - style.scss



